### ISSUE TITLE
What should we use for REDIRECT_URI?

### ISSUE THREAD

**Issue by InterwebCounty** [jacobian/rdio2spotify#2]
Sorry, I can't figure that part out.

**Comment by peiitforward** [comment]
I just used 'https://www.google.com/' so when I run r2s.py I get redirected to google in my browser. Then I just copy and paste the URL it spits out back into terminal.

**Comment by InterwebCounty** [comment]
Thank that worked!  Also very important to have that slash at the end.

Now my only problem is Spotify, I'm not loving it so far.
