### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by jodonnell** [jacobian/rdio2spotify#3]
rdio_export_to_sqlite.py

click.secho("collection.csv doesn't exist, bailing", fg=red)
should be
click.secho("collection.csv doesn't exist, bailing", fg='red')

I think anyway!!

**Comment by schneems** [comment]
For small stuff like this it's usually okay to make a PR, makes it way easier to fix, just have to click the merge button. I edited the file directly in github and made a PR https://github.com/jacobian/rdio2spotify/pull/4.

**Comment by jacobian** [comment]
Fixed in #4
